import type { CMSData } from "./types";
import { blogPosts } from "@/lib/blog";

const BASE_PRODUCTS = [
  { id: "1228429", name: "fēnix® 8", price: 799.99, priceSuffix: "and up", description: "Premium multisport GPS smartwatches with options that include inReach® technology for connectivity on the go.", image: "/images/products/1228429.jpg", badge: "CUSTOMIZABLE", family: "fēnix", activities: ["Hiking", "Running", "Swimming", "Triathlon", "Diving"], level: "Premium" as const, caseSize: "Medium" as const },
  { id: "1614061", name: "Venu® 4", price: 549.99, description: "Advanced health and fitness GPS smartwatches with bright, colorful displays, a built-in flashlight, and wellness and smart features.", image: "/images/products/1614061.jpg", badge: "CUSTOMIZABLE", family: "Venu", activities: ["Running", "Strength", "Swimming", "Walking"], level: "Advanced" as const, caseSize: "Medium" as const },
  { id: "1462801", name: "Forerunner® 970", price: 749.99, description: "Premium GPS running and triathlon smartwatch with an AMOLED display, built-in LED flashlight and enhanced navigation plus advanced training and recovery features.", image: "/images/products/1462801.jpg", badge: "NONE", family: "Forerunner", activities: ["Running", "Triathlon", "Cycling", "Swimming"], level: "Premium" as const, caseSize: "Medium" as const },
  { id: "1510465", name: "Venu® X1", price: 699.99, description: "Sleek, lightweight GPS smartwatch with a bright 2-inch AMOLED display and advanced health and fitness features.", image: "/images/products/1510465.jpg", badge: "NONE", family: "Venu", activities: ["Running", "Strength", "Walking"], level: "Advanced" as const, caseSize: "Large" as const },
  { id: "1463821", name: "Forerunner® 570", price: 549.99, description: "Advanced GPS running and triathlon smartwatches with AMOLED displays plus training and recovery features.", image: "/images/products/1463821.jpg", badge: "CUSTOMIZABLE", family: "Forerunner", activities: ["Running", "Triathlon", "Cycling"], level: "Advanced" as const, caseSize: "Medium" as const },
  { id: "1941179", name: "Forerunner® 70/170", price: 249.99, priceSuffix: "and up", description: "GPS running smartwatches with essential training and recovery features, plus optional music.", image: "/images/products/1941179.jpg", badge: "NEW", family: "Forerunner", activities: ["Running", "Walking"], level: "Entry" as const, caseSize: "Small" as const },
  { id: "1316397", name: "Instinct® 3", price: 249.99, priceSuffix: "and up", description: "Rugged GPS smartwatches with dedicated tactical features and solar charging or AMOLED displays.", image: "/images/products/1316397.jpg", badge: "CUSTOMIZABLE", family: "Instinct", activities: ["Hiking", "Tactical training", "Running"], level: "Advanced" as const, caseSize: "Medium" as const },
  { id: "1555457", name: "vívoactive® 6", price: 299.99, description: "Health and fitness GPS smartwatch with a bright, colorful display and essential fitness, wellness and smart features.", image: "/images/products/1555457.jpg", badge: "NONE", family: "vívoactive", activities: ["Running", "Walking", "Strength"], level: "Entry" as const, caseSize: "Small" as const },
  { id: "1800201", name: "Instinct® Crossover", price: 399.99, priceSuffix: "and up", description: "Hybrid outdoor GPS smartwatches with options for solar charging or AMOLED displays.", image: "/images/products/1800201.jpg", badge: "NONE", family: "Instinct", activities: ["Hiking", "Tactical training", "Running"], level: "Advanced" as const, caseSize: "Medium" as const },
  { id: "1828641", name: "tactix® 8", price: 1299.99, priceSuffix: "and up", description: "Premium tactical GPS smartwatches with solar charging or AMOLED displays.", image: "/images/products/1828641.jpg", badge: "NONE", family: "tactix", activities: ["Tactical training", "Flying", "Diving", "Hiking"], level: "Premium" as const, caseSize: "Large" as const },
  { id: "851039", name: "Enduro™ 3", price: 899.99, description: "Ultraperformance smartwatch with GPS plus advanced training metrics and maps.", image: "/images/products/851039.jpg", badge: "NONE", family: "Enduro", activities: ["Running", "Hiking", "Triathlon"], level: "Premium" as const, caseSize: "Large" as const },
  { id: "1196650", name: "Lily® 2", price: 249.99, priceSuffix: "and up", description: "Small fashion smartwatch with essential wellness and smart features plus optional GPS.", image: "/images/products/1196650.jpg", badge: "NONE", family: "Lily", activities: ["Walking", "Strength"], level: "Entry" as const, caseSize: "Small" as const },
  { id: "1815501", name: "Bounce™ 2", price: 299.99, description: "Kids smartwatch with calling, messaging and location tracking features.", image: "/images/products/1815501.jpg", badge: "NONE", family: "Bounce", activities: ["Walking"], level: "Youth" as const, caseSize: "Small" as const },
  { id: "1908217", name: "Approach® J1", price: 299.99, description: "Junior golf watch with built-in GPS, a bright, colorful display and essential features.", image: "/images/products/1908217.jpg", badge: "NONE", family: "Approach", activities: ["Golfing"], level: "Youth" as const, caseSize: "Small" as const },
  { id: "1765781", name: "MARQ® (Gen 2)", price: 1900.0, priceSuffix: "and up", description: "Luxury GPS tool watches with AMOLED displays, premium materials and multisport capabilities.", image: "/images/products/1765781.jpg", badge: "CUSTOMIZABLE", family: "MARQ", activities: ["Hiking", "Flying", "Boating"], level: "Premium" as const, caseSize: "Large" as const },
  { id: "785411", name: "vívomove®", price: 269.99, priceSuffix: "and up", description: "Hybrid smartwatches with hidden displays, essential wellness tracking and smart features.", image: "/images/products/785411.jpg", badge: "NONE", family: "vívomove", activities: ["Walking", "Strength"], level: "Entry" as const, caseSize: "Small" as const },
  { id: "847706", name: "Approach® S70", price: 649.99, priceSuffix: "and up", description: "Premium golf smartwatch with GPS, an AMOLED display and advanced wellness and on-course features.", image: "/images/products/847706.jpg", badge: "NONE", family: "Approach", activities: ["Golfing"], level: "Premium" as const, caseSize: "Medium" as const },
];

export const initialCMSData: CMSData = {
  admins: [
    {
      id: "admin-1",
      name: "Garmin Super Admin",
      email: "admin@garmin.com",
      password: "admin123",
      role: "super_admin",
      status: "active",
      avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
      createdAt: "2026-01-01T00:00:00.000Z",
      lastLogin: new Date().toISOString(),
    },
    {
      id: "admin-2",
      name: "Marcus Vance",
      email: "marcus.vance@garmin.com",
      password: "admin123",
      role: "product_manager",
      status: "active",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
      createdAt: "2026-01-15T00:00:00.000Z",
      lastLogin: "2026-08-15T14:20:00.000Z",
    },
    {
      id: "admin-3",
      name: "Elena Rostova",
      email: "elena.r@garmin.com",
      password: "admin123",
      role: "editor",
      status: "active",
      avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
      createdAt: "2026-02-01T00:00:00.000Z",
      lastLogin: "2026-08-16T09:12:00.000Z",
    },
  ],

  clients: [
    {
      id: "client-1",
      name: "Alexander Hayes",
      email: "a.hayes@aviation-ventures.com",
      phone: "+65 9123 4567",
      country: "Singapore",
      status: "vip",
      totalSpent: 4850.0,
      ordersCount: 4,
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
      notes: "MARQ Aviator Gen 2 owner. Frequent luxury buyer.",
      createdAt: "2026-01-10T08:00:00.000Z",
    },
    {
      id: "client-2",
      name: "Samantha Wright",
      email: "sam.wright@tri-athletes.org",
      phone: "+1 (555) 234-5678",
      country: "United States",
      status: "active",
      totalSpent: 1649.98,
      ordersCount: 2,
      avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
      notes: "Ironman athlete. Purchased Forerunner 970 and HRM-Pro Plus.",
      createdAt: "2026-02-14T11:30:00.000Z",
    },
    {
      id: "client-3",
      name: "David Tanaka",
      email: "dtanaka@marine-sailing.jp",
      phone: "+81 3 5555 0199",
      country: "Japan",
      status: "vip",
      totalSpent: 3800.0,
      ordersCount: 3,
      avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80",
      notes: "MARQ Captain & Quatix collector.",
      createdAt: "2026-03-05T09:15:00.000Z",
    },
    {
      id: "client-4",
      name: "Sophie Dupont",
      email: "sophie.dupont@alpine-trail.fr",
      phone: "+33 6 12 34 56 78",
      country: "France",
      status: "active",
      totalSpent: 799.99,
      ordersCount: 1,
      avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80",
      notes: "Purchased fēnix 8 47mm AMOLED Titanium.",
      createdAt: "2026-04-12T14:45:00.000Z",
    },
    {
      id: "client-5",
      name: "Michael Chang",
      email: "mchang@pacific-capital.sg",
      phone: "+65 8234 5678",
      country: "Singapore",
      status: "active",
      totalSpent: 1299.99,
      ordersCount: 2,
      avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80",
      createdAt: "2026-05-20T16:20:00.000Z",
    },
    {
      id: "client-6",
      name: "Liam O'Connor",
      email: "liam.oc@dublin-run.ie",
      phone: "+353 87 123 4567",
      country: "Ireland",
      status: "pending",
      totalSpent: 0.0,
      ordersCount: 0,
      avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80",
      createdAt: "2026-08-16T18:00:00.000Z",
    },
  ],

  products: [
    ...BASE_PRODUCTS.map((p, idx) => {
      const isFenix = p.family.includes("fēnix");
      const isForerunner = p.family.includes("Forerunner");
      const isVenu = p.family.includes("Venu");
      const isInstinct = p.family.includes("Instinct");

      const category = isFenix
        ? "Smartwatches & Wearables"
        : isForerunner
        ? "Sports & Fitness"
        : isVenu
        ? "Fashion & Wellness"
        : isInstinct
        ? "Outdoor Recreation"
        : "Smartwatches & Wearables";

      const subCategory = isFenix
        ? "Multisport GPS"
        : isForerunner
        ? "Running GPS"
        : isVenu
        ? "Fashion & Wellness"
        : isInstinct
        ? "Diving & Tactical"
        : "Smartwatches";

      return {
        id: p.id,
        name: p.name,
        sku: `GRM-${p.id}`,
        price: p.price,
        originalPrice: p.price * 1.15,
        priceSuffix: p.priceSuffix,
        description: p.description,
        image: p.image,
        badge: p.badge || (idx === 0 ? "CUSTOMIZABLE" : idx === 1 ? "NEW" : "NONE"),
        family: p.family,
        category,
        subCategory,
        activities: p.activities,
        level: p.level,
        caseSize: p.caseSize,
        stock: 45 + ((idx * 7) % 60),
        status: "published" as const,
        isFeatured: idx < 6,
        specs: [
          { label: "Lens Material", value: isFenix ? "Sapphire Crystal" : "Corning® Gorilla® Glass 3" },
          { label: "Bezel Material", value: isFenix ? "Titanium" : "Stainless Steel / Polymer" },
          { label: "Display", value: '1.4" AMOLED Display (454 x 454 pixels)' },
          { label: "Battery Life", value: "Smartwatch: Up to 16 days (7 days always-on)" },
          { label: "Water Rating", value: isFenix ? "10 ATM / 40m Dive" : "5 ATM (50 meters)" },
          { label: "Memory / History", value: "32 GB onboard storage" },
        ],
        inTheBox: [
          `${p.name} Smartwatch`,
          "USB-C Charging / Data Clip Cable",
          "Quick-Start Manual & Warranty Booklet",
          "Alternative QuickFit Silicone Strap",
        ],
        compatibleAccessories: [
          "acc-hrm-pro-plus",
          "acc-qf22-silicone-black",
          "acc-speed-cadence",
        ],
        features: [
          {
            title: "Advanced Health & Fitness Tracking",
            body: "24/7 heart rate monitoring, Body Battery™ energy tracking, Pulse Ox, sleep coach, and nap detection.",
          },
          {
            title: "Multi-Band GNSS & TopoActive Maps",
            body: "Multi-frequency positioning with SatIQ™ technology delivers superior tracking accuracy in challenging environments.",
          },
        ],
        createdAt: "2026-01-01T00:00:00.000Z",
      };
    }),

    // MARQ Luxury Collection 7 Models
    {
      id: "marq-captain",
      name: "MARQ® Captain (Gen 2)",
      sku: "010-02648-11",
      price: 2200.0,
      description: "Luxury modern tool watch crafted from Grade-5 titanium with navy ceramic regatta timer bezel and jacquard-weave nylon strap.",
      image: "/marq/images/marq-spec-captain.png",
      badge: "EXCLUSIVE",
      family: "MARQ",
      category: "Luxury Tool Watches (MARQ)",
      subCategory: "Marine & Sailing",
      activities: ["Boating", "Swimming", "Hiking"],
      level: "Premium",
      caseSize: "Medium",
      stock: 18,
      status: "published",
      isFeatured: true,
      specs: [
        { label: "Lens Material", value: "Domed Sapphire Crystal" },
        { label: "Bezel Material", value: "Grade-5 Titanium with Navy Ceramic Inlay" },
        { label: "Display", value: '1.2" AMOLED Touchscreen (390 x 390 pixels)' },
        { label: "Battery Life", value: "Up to 16 days (Smartwatch mode)" },
        { label: "Water Rating", value: "10 ATM (100 meters)" },
        { label: "Strap Material", value: "Jacquard-weave striped nylon with titanium buckle" },
      ],
      inTheBox: [
        "MARQ® Captain (Gen 2)",
        "Navy blue jacquard-weave nylon strap",
        "Alternative navy blue silicone rubber watch strap",
        "Magnetic USB-C fast charger cable",
        "Luxury presentation case & documentation",
      ],
      compatibleAccessories: [
        "acc-hrm-pro-plus",
        "acc-qf22-silicone-black",
      ],
      createdAt: "2026-02-01T00:00:00.000Z",
    },
    {
      id: "marq-adventurer-damascus",
      name: "MARQ® Adventurer (Gen 2) Damascus Steel Edition",
      sku: "010-02648-51",
      price: 3100.0,
      description: "Forged from Damascus steel with 360-degree compass bezel and hybrid leather/FKM rubber strap.",
      image: "/marq/images/marq-spec-damascus.png",
      badge: "LIMITED EDITION",
      family: "MARQ",
      category: "Luxury Tool Watches (MARQ)",
      subCategory: "Multisport GPS",
      activities: ["Hiking", "Running", "Tactical training"],
      level: "Premium",
      caseSize: "Medium",
      stock: 9,
      status: "published",
      isFeatured: true,
      specs: [
        { label: "Lens Material", value: "Domed Sapphire Crystal" },
        { label: "Bezel Material", value: "Hand-forged Damascus Steel with 360° Compass" },
        { label: "Display", value: '1.2" AMOLED Touchscreen (390 x 390 pixels)' },
        { label: "Battery Life", value: "Up to 16 days (Smartwatch mode)" },
        { label: "Water Rating", value: "10 ATM (100 meters)" },
        { label: "Strap Material", value: "Sweat-resistant Italian leather with FKM rubber lining" },
      ],
      inTheBox: [
        "MARQ® Adventurer (Gen 2) Damascus Steel Edition",
        "Hybrid leather/FKM rubber strap",
        "Black silicone rubber strap",
        "Magnetic USB-C fast charging clip",
        "Collector's wooden gift box & certificate of authenticity",
      ],
      compatibleAccessories: [
        "acc-hrm-pro-plus",
        "acc-qf22-silicone-black",
      ],
      createdAt: "2026-02-15T00:00:00.000Z",
    },
    {
      id: "marq-carbon-golfer",
      name: "MARQ® Golfer (Gen 2) Carbon Edition",
      sku: "010-02722-11",
      price: 2950.0,
      description: "Machined from a solid block of Fused Carbon Fiber with custom French-woven jacquard strap.",
      image: "/marq/images/marq-spec-carbon-golfer.png",
      badge: "CARBON FIBER",
      family: "MARQ",
      category: "Luxury Tool Watches (MARQ)",
      subCategory: "Golf Smartwatches",
      activities: ["Golfing"],
      level: "Premium",
      caseSize: "Medium",
      stock: 14,
      status: "published",
      isFeatured: true,
      specs: [
        { label: "Lens Material", value: "Domed Sapphire Crystal" },
        { label: "Bezel Material", value: "130-layer Fused Carbon Fiber with Custom Inlay" },
        { label: "Display", value: '1.2" AMOLED Touchscreen (390 x 390 pixels)' },
        { label: "Battery Life", value: "Up to 16 days (Smartwatch mode)" },
        { label: "Water Rating", value: "10 ATM (100 meters)" },
        { label: "Preloaded Courses", value: "43,000+ full-color CourseView maps" },
      ],
      inTheBox: [
        "MARQ® Golfer (Gen 2) Carbon Edition",
        "French jacquard-weave nylon strap",
        "Pine green silicone rubber strap",
        "3x Approach® CT10 club tracking sensors",
        "USB-C fast magnetic charging cable",
      ],
      compatibleAccessories: [
        "acc-speed-cadence",
        "acc-hrm-pro-plus",
      ],
      createdAt: "2026-03-01T00:00:00.000Z",
    },
  ],

  discounts: [
    {
      id: "disc-1",
      code: "GARMIN20",
      description: "20% off all wearables & smartwatches",
      type: "percentage",
      value: 20,
      minSpend: 200,
      usageLimit: 500,
      perCustomerLimit: 1,
      usageCount: 142,
      applyType: "categories",
      targetCategories: ["Smartwatches & Wearables", "Sports & Fitness"],
      startDate: "2026-01-01T00:00:00.000Z",
      expiresAt: "2026-12-31T23:59:59.000Z",
      isStackable: false,
      status: "active",
      createdAt: "2026-01-01T00:00:00.000Z",
    },
    {
      id: "disc-2",
      code: "MARQVIP",
      description: "$200 instant luxury discount on MARQ Collection",
      type: "fixed",
      value: 200,
      minSpend: 1500,
      usageLimit: 100,
      perCustomerLimit: 1,
      usageCount: 28,
      applyType: "skus",
      targetSkus: ["010-02648-11", "010-02648-51", "010-02722-11"],
      startDate: "2026-02-01T00:00:00.000Z",
      expiresAt: "2026-10-31T23:59:59.000Z",
      isStackable: true,
      status: "active",
      createdAt: "2026-02-01T00:00:00.000Z",
    },
    {
      id: "disc-3",
      code: "WELCOME10",
      description: "10% discount for first-time buyers on all store products",
      type: "percentage",
      value: 10,
      minSpend: 100,
      usageLimit: 2000,
      perCustomerLimit: 1,
      usageCount: 685,
      applyType: "all",
      startDate: "2026-01-01T00:00:00.000Z",
      expiresAt: "2026-12-31T23:59:59.000Z",
      isStackable: false,
      status: "active",
      createdAt: "2026-01-01T00:00:00.000Z",
    },
    {
      id: "disc-4",
      code: "SUMMER15",
      description: "Summer outdoor adventure 15% discount",
      type: "percentage",
      value: 15,
      minSpend: 250,
      usageLimit: 300,
      perCustomerLimit: 2,
      usageCount: 300,
      applyType: "categories",
      targetCategories: ["Outdoor Recreation", "Sports & Fitness"],
      startDate: "2026-06-01T00:00:00.000Z",
      expiresAt: "2026-08-01T00:00:00.000Z",
      isStackable: false,
      status: "expired",
      createdAt: "2026-06-01T00:00:00.000Z",
    },
  ],

  banners: [
    {
      id: "banner-1",
      title: "MARQ® (Gen 2) Collection",
      subtitle: "Where luxury and performance collide. Seven modern tool watches forged from titanium, carbon and Damascus steel.",
      ctaLabel: "Explore MARQ",
      ctaUrl: "/minisite/marq",
      image: "/marq/images/kv-bg.jpg",
      position: "hero",
      active: true,
      order: 1,
      createdAt: "2026-01-01T00:00:00.000Z",
    },
    {
      id: "banner-2",
      title: "fēnix® 8 Series",
      subtitle: "Be your best. Multisport GPS smartwatches built for athletes with AMOLED display and mic/speaker.",
      ctaLabel: "Shop fēnix 8",
      ctaUrl: "/minisite/fenix-8",
      image: "/images/hero/fenix8-hero.jpg",
      position: "hero",
      active: true,
      order: 2,
      createdAt: "2026-01-10T00:00:00.000Z",
    },
    {
      id: "banner-3",
      title: "Garmin Pay™ Contactless Payment",
      subtitle: "Leave your cards and phone behind. Pay on the go with your wrist.",
      ctaLabel: "Learn More",
      ctaUrl: "/minisite/garmin-pay",
      image: "/images/hero/garmin-pay-hero.jpg",
      position: "promo_pod",
      active: true,
      order: 3,
      createdAt: "2026-02-01T00:00:00.000Z",
    },
    {
      id: "banner-4",
      title: "Enjoy Free Express Shipping on orders over $150 | Official Garmin Guarantee",
      image: "/marq/images/kv-bg.jpg",
      position: "announcement",
      active: true,
      order: 1,
      createdAt: "2026-01-01T00:00:00.000Z",
    },
  ],

  blogs: blogPosts.map((b, i) => ({
    id: `blog-${i + 1}`,
    slug: b.slug,
    title: b.title,
    excerpt: b.excerpt,
    content: b.excerpt + "\n\nDiscover all Garmin training features, wellness insights, and smart metrics to elevate your performance to the next level.",
    coverImage: b.image,
    category: b.category,
    readingTime: b.readTime || "5 min read",
    author: "Garmin Editorial Team",
    status: "published" as const,
    publishedAt: b.date,
    createdAt: "2026-01-01T00:00:00.000Z",
  })),

  orders: [
    {
      id: "ord-1001",
      orderNumber: "GRM-89241",
      clientName: "Alexander Hayes",
      clientEmail: "a.hayes@aviation-ventures.com",
      total: 2200.0,
      itemsCount: 1,
      items: [
        {
          productId: "marq-captain",
          name: "MARQ® Captain (Gen 2)",
          price: 2200.0,
          quantity: 1,
          image: "/marq/images/marq-spec-captain.png",
        },
      ],
      paymentStatus: "paid",
      fulfillmentStatus: "delivered",
      shippingAddress: "12 Marina Boulevard, #34-01 MBFC Tower 3, Singapore 018982",
      createdAt: "2026-08-10T14:32:00.000Z",
    },
    {
      id: "ord-1002",
      orderNumber: "GRM-89242",
      clientName: "Samantha Wright",
      clientEmail: "sam.wright@tri-athletes.org",
      total: 899.98,
      itemsCount: 2,
      items: [
        {
          productId: "1462801",
          name: "Forerunner® 970",
          price: 749.99,
          quantity: 1,
          image: "/images/products/1462801.jpg",
        },
        {
          productId: "hrm-pro-plus",
          name: "HRM-Pro™ Plus Heart Rate Monitor",
          price: 149.99,
          quantity: 1,
          image: "/images/products/1228429.jpg",
        },
      ],
      paymentStatus: "paid",
      fulfillmentStatus: "shipped",
      shippingAddress: "742 Evergreen Terrace, Springfield, IL 62704, USA",
      createdAt: "2026-08-14T09:18:00.000Z",
    },
    {
      id: "ord-1003",
      orderNumber: "GRM-89243",
      clientName: "Sophie Dupont",
      clientEmail: "sophie.dupont@alpine-trail.fr",
      total: 799.99,
      itemsCount: 1,
      items: [
        {
          productId: "1228429",
          name: "fēnix® 8 - 47 mm, AMOLED",
          price: 799.99,
          quantity: 1,
          image: "/images/products/1228429.jpg",
        },
      ],
      paymentStatus: "paid",
      fulfillmentStatus: "processing",
      shippingAddress: "24 Rue de la Paix, 75002 Paris, France",
      createdAt: "2026-08-16T11:45:00.000Z",
    },
    {
      id: "ord-1004",
      orderNumber: "GRM-89244",
      clientName: "David Tanaka",
      clientEmail: "dtanaka@marine-sailing.jp",
      total: 3100.0,
      itemsCount: 1,
      items: [
        {
          productId: "marq-adventurer-damascus",
          name: "MARQ® Adventurer Damascus Steel",
          price: 3100.0,
          quantity: 1,
          image: "/marq/images/marq-spec-damascus.png",
        },
      ],
      paymentStatus: "paid",
      fulfillmentStatus: "processing",
      shippingAddress: "4-1-1 Ginza, Chuo-ku, Tokyo 104-0061, Japan",
      createdAt: "2026-08-16T16:20:00.000Z",
    },
  ],

  settings: {
    storeName: "Garmin Singapore Official Store",
    contactEmail: "support@garmin.com.sg",
    supportPhone: "+65 6775 8899",
    currency: "SGD",
    currencySymbol: "S$",
    freeShippingThreshold: 150,
    taxRate: 9.0,
    maintenanceMode: false,
    garminPaySandbox: true,
    stripeEnabled: true,
    seoTitle: "Garmin Singapore | Official Smartwatches, GPS & Wearables Store",
    seoDescription: "Explore Garmin smartwatch collections including MARQ Gen 2, fēnix 8, Forerunner, Venu and Garmin Pay.",
  },

  activities: [
    {
      id: "act-1",
      adminName: "Garmin Super Admin",
      action: "Published new collection",
      target: "MARQ (Gen 2) Damascus Steel Edition",
      timestamp: "2026-08-16T17:00:00.000Z",
    },
    {
      id: "act-2",
      adminName: "Marcus Vance",
      action: "Updated inventory stock",
      target: "fēnix 8 Titanium AMOLED (+25 units)",
      timestamp: "2026-08-16T15:30:00.000Z",
    },
    {
      id: "act-3",
      adminName: "Elena Rostova",
      action: "Published blog article",
      target: "How to Train for a Triathlon with Garmin",
      timestamp: "2026-08-15T11:00:00.000Z",
    },
    {
      id: "act-4",
      adminName: "Garmin Super Admin",
      action: "Created discount campaign",
      target: "MARQVIP ($200 off)",
      timestamp: "2026-08-14T09:00:00.000Z",
    },
  ],
};
